[FAB-17632] Exclude unnecessary code from ecdsa.go
hyperledger/fabric-sdk-go pull request #60
Opened 2020-03-17 13:59 UTC by VadimInshakov

Fixed GenSKI() for clean code.

2020-03-19 18:16 UTC, kopaygorodsky requested changes

2020-03-19 18:16 UTC, kopaygorodsky commented on scripts/_go/src/pkcs11helper/pkg/pkcs11wrapper/ecdsa.go
> +		return errors.New(fmt.Sprintf("Failed to write hash, error: %s", err))
why new error? use Wrapf

2020-03-19 18:16 UTC, kopaygorodsky commented on scripts/_go/src/pkcs11helper/pkg/pkcs11wrapper/ecdsa.go
> +		return errors.New(fmt.Sprintf("Failed to write hash, error: %s", err))
errors.Wrapf

2020-03-19 18:16 UTC, kopaygorodsky commented on scripts/_go/src/pkcs11helper/pkg/pkcs11wrapper/pkcs11.go
> +		err = errors.New(fmt.Sprintf("failed to generate SKI, error: %s", err))
errors.Wrapf

2020-03-20 07:28 UTC, VadimInshakov commented on scripts/_go/src/pkcs11helper/pkg/pkcs11wrapper/ecdsa.go
> +		return errors.New(fmt.Sprintf("Failed to write hash, error: %s", err))
Ok!

2020-03-20 07:29 UTC, VadimInshakov commented on scripts/_go/src/pkcs11helper/pkg/pkcs11wrapper/ecdsa.go
> +		return errors.New(fmt.Sprintf("Failed to write hash, error: %s", err))
Ok!

2020-03-20 07:29 UTC, VadimInshakov commented on scripts/_go/src/pkcs11helper/pkg/pkcs11wrapper/pkcs11.go
> +		err = errors.New(fmt.Sprintf("failed to generate SKI, error: %s", err))
Ok!

2020-03-20 15:15 UTC, troyronda commented
@VadimInshakov Thanks for your contribution. Please update your commit and PR with DCO sign-off.

2020-03-21 14:57 UTC, VadimInshakov commented
@troyronda ok, done.

2020-03-23 10:03 UTC, VadimInshakov commented
@troyronda is there any updates?

2020-03-23 12:38 UTC, troyronda approved these changes

2020-03-23 13:08 UTC, merged